@echo off
echo Alternative bcrypt fix...
echo Uninstalling bcrypt...
npm uninstall bcrypt
echo Installing bcrypt with rebuild...
npm install bcrypt --build-from-source
echo If that fails, trying bcryptjs as alternative...
npm uninstall bcrypt
npm install bcryptjs
echo Done! Update your code to use bcryptjs instead of bcrypt if needed.
pause