@echo off
echo Fixing bcrypt issue...
echo Removing node_modules folder...
rmdir /s /q node_modules
echo Removing package-lock.json...
del package-lock.json
echo Clearing npm cache...
npm cache clean --force
echo Reinstalling dependencies...
npm install
echo Done! Try running your project again.
pause